name: Build and push Docker image on release

on:
  release:
    types: [ published ]
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  docker_push:
    name: Build & push Docker image
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/docker_push.yml
    with:
      image-tags: ${{ inputs.tag || github.event.release.tag_name }}
